--
--19890826-T558
--Chris Gkalfas
--4ME302 - Foundations of Computational Media - HT17
--Second-Assignment
--

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+03:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`users`(
  `id` INT(11) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(255) DEFAULT 'images/default.jpg',
  `provider` VARCHAR(255) DEFAULT NULL,
  `provider_id` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `email`, `avatar`, `provider`, `provider_id`) VALUES
(1, 'chris', 'test123', 'email@example.com', 'images/default.jpg', NULL, NULL);


--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 23:10:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Medicine` (
  `medicineID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`medicineID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Organization` (
  `OrganizationID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`OrganizationID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Role` (
  `roleID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`User` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `Role_IDrole` INT(11) NOT NULL,
  `Organization` INT(11) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `roleID_idx` (`Role_IDrole` ASC),
  INDEX `fk_User_Organization_idx` (`Organization` ASC),
  CONSTRAINT `fk_User_Organization`
    FOREIGN KEY (`Organization`)
    REFERENCES `Fblogin-31370db2`.`Organization` (`OrganizationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_IDrole`)
    REFERENCES `Fblogin-31370db2`.`Role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Therapy_List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Therapy_List` (
  `therapy_listID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Medicine_IDmedicine` INT(11) NOT NULL,
  `Dosage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`therapy_listID`),
  INDEX `fk_medicineID_idx` (`Medicine_IDmedicine` ASC),
  CONSTRAINT `fk_MedicineID`
    FOREIGN KEY (`Medicine_IDmedicine`)
    REFERENCES `Fblogin-31370db2`.`Medicine` (`medicineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Therapy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pd_db`.`Therapy` (
  `therapyID` INT(11) NOT NULL AUTO_INCREMENT,
  `User_IDpatient` INT(11) NOT NULL,
  `User_IDmed` INT(11) NOT NULL,
  `TherapyList_IDtherapylist` INT(11) NOT NULL,
  PRIMARY KEY (`therapyID`),
  INDEX `fk_UserID_Patient_idx` (`User_IDpatient` ASC),
  INDEX `fk_UserID_medic_idx` (`User_IDmed` ASC),
  INDEX `fk_Therapy_ListID_idx` (`TherapyList_IDtherapylist` ASC),
  CONSTRAINT `fk_Therapy_ListID`
    FOREIGN KEY (`TherapyList_IDtherapylist`)
    REFERENCES `Fblogin-31370db2`.`Therapy_List` (`therapy_listID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserID_medic`
    FOREIGN KEY (`User_IDmed`)
    REFERENCES `Fblogin-31370db2`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserID_Patient`
    FOREIGN KEY (`User_IDpatient`)
    REFERENCES `Fblogin-31370db2`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Test` (
  `testID` INT(11) NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `Therapy_IDtherapy` INT(11) NOT NULL,
  PRIMARY KEY (`testID`),
  INDEX `fk_TherapyID_idx` (`Therapy_IDtherapy` ASC),
  CONSTRAINT `fk_TherapyID`
    FOREIGN KEY (`Therapy_IDtherapy`)
    REFERENCES `Fblogin-31370db2`.`Therapy` (`therapyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Test_Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Test_Session` (
  `test_SessionID` INT(11) NOT NULL AUTO_INCREMENT,
  `type` INT(11) NOT NULL,
  `Test_IDtest` INT(11) NOT NULL,
  `DataURL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`test_SessionID`),
  INDEX `fk_TestID_idx` (`Test_IDtest` ASC),
  CONSTRAINT `fk_TestID`
    FOREIGN KEY (`Test_IDtest`)
    REFERENCES `Fblogin-31370db2`.`Test` (`testID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Fblogin-31370db2`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fblogin-31370db2`.`Note` (
  `noteID` INT(11) NOT NULL AUTO_INCREMENT,
  `Test_Session_IDtest_session` INT(11) NOT NULL,
  `note` LONGTEXT NOT NULL,
  `User_IDmed` INT(11) NOT NULL,
  PRIMARY KEY (`noteID`),
  INDEX `fk_Test_SessionID_idx` (`Test_Session_IDtest_session` ASC),
  INDEX `fk_UserID_idx` (`User_IDmed` ASC),
  CONSTRAINT `fk_UserID`
    FOREIGN KEY (`User_IDmed`)
    REFERENCES `Fblogin-31370db2`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_SessionID`
    FOREIGN KEY (`Test_Session_IDtest_session`)
    REFERENCES `Fblogin-31370db2`.`Test_Session` (`test_SessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

